{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ddfe58ed",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "df=pd.read_html('https://www.monasterio-tattersall.com/precios-hacienda') #leo la tabla de la página\n",
    "df[0] \n",
    "hacienda = df[0] #asigno una variable a la tabla\n",
    "categoria = hacienda.Categoría #creo las series\n",
    "promedio = hacienda.Promedio\n",
    "tabla = pd.DataFrame({'categoria':categoria,'promedio':promedio}) #creo un dataframe con categoria y promedio\n",
    "ternero=tabla[0:4] \n",
    "novillito=tabla[4:7]\n",
    "ternera=tabla[7:11]\n",
    "vaquillona=tabla[11:14]\n",
    "vaca=tabla[19:20]\n",
    "fecha=(tabla[25:26].values)[0][0]\n",
    "ternero160=int(ternero.promedio[0][2:5])\n",
    "ternero180=int(ternero.promedio[1][2:5])\n",
    "ternero200=int(ternero.promedio[2][2:5])\n",
    "ternero230=int(ternero.promedio[3][2:5])\n",
    "novillo260=int(novillito.promedio[4][2:5])\n",
    "novillo300=int(novillito.promedio[5][2:5])\n",
    "novillo301=int(novillito.promedio[6][2:5])\n",
    "ternera150=int(ternera.promedio[7][2:5])\n",
    "ternera170=int(ternera.promedio[8][2:5])\n",
    "ternera190=int(ternera.promedio[9][2:5])\n",
    "ternera210=int(ternera.promedio[10][2:5])\n",
    "vaquillona250=int(vaquillona.promedio[11][2:5])\n",
    "vaquillona290=int(vaquillona.promedio[12][2:5])\n",
    "vaquillona291=int(vaquillona.promedio[13][2:5])\n",
    "vacas=int(vaca.promedio[19][2:8])\n",
    "def constructor():\n",
    "    tipo=input('ingrese tipo de hacienda: \\n1 - Ternero\\n2 - Novillito\\n3 - Ternera\\n4 - Vaquillona\\n5 - Vaca\\n')\n",
    "    if tipo =='1':\n",
    "        categoria='Ternero'\n",
    "    elif tipo == '2':\n",
    "        categoria='Novillito'\n",
    "    elif tipo == '3':\n",
    "        categoria='Ternera'\n",
    "    elif tipo == '4':\n",
    "        categoria='Vaquillona'\n",
    "    elif tipo == '5':\n",
    "        categoria='Vaca'\n",
    "    cantidad=int(input('ingrese cantidad: '))\n",
    "    peso=int(input('ingrese peso: '))\n",
    "    def valores():\n",
    "        if tipo == '1' and peso < 160:\n",
    "            valor = ternero160*cantidad*peso\n",
    "        elif tipo == '1' and peso < 180:\n",
    "            valor = ternero180*cantidad*peso\n",
    "        elif tipo == '1' and peso <= 200:\n",
    "            valor = ternero200*cantidad*peso\n",
    "        elif tipo == '1' and peso > 200:\n",
    "            valor = ternero230*cantidad*peso\n",
    "        elif tipo == '1' and peso == 0:\n",
    "            valor = ternero200*cantidad*peso\n",
    "        elif tipo == '2' or 'novillo' and peso < 260:\n",
    "            valor = novillo260*cantidad*peso\n",
    "        elif tipo == '2' or 'novillo'and peso <= 300:\n",
    "            valor = novillo300*cantidad*peso\n",
    "        elif tipo == '2' or 'novillo'and peso > 300:\n",
    "            valor = novillo301*cantidad*peso\n",
    "        elif tipo == '2' or 'novillo'and peso == 0:\n",
    "            valor = novillo300*cantidad*peso\n",
    "        elif tipo == '3' and peso < 150:\n",
    "            valor = ternera150*cantidad*peso\n",
    "        elif tipo == '3' and peso < 170:\n",
    "            valor = ternera170*cantidad*peso\n",
    "        elif tipo == '3' and peso <= 190:\n",
    "            valor = ternera190*cantidad*peso\n",
    "        elif tipo == '3' and peso > 190:\n",
    "            valor = ternera210*cantidad*peso\n",
    "        elif tipo == '3' and peso == 0:\n",
    "            valor = ternera190*cantidad*peso\n",
    "        elif tipo == '4' and peso < 250:\n",
    "            valor = vaquillona250*cantidad*peso\n",
    "        elif tipo == '4' and peso <= 290:\n",
    "            valor = vaquillona290*cantidad*peso\n",
    "        elif tipo == '4' and peso > 290:\n",
    "            valor = vaquillona291*cantidad*peso\n",
    "        elif tipo == '4' and peso == 0:\n",
    "            valor = vaquillona290*cantidad*peso\n",
    "        elif tipo == '5':\n",
    "            valor = vacas*cantidad\n",
    "        return valor\n",
    "    valor=valores()\n",
    "    d = [categoria, cantidad, peso, valor]\n",
    "    return d\n",
    "metalista=[]\n",
    "def programa():\n",
    "    while True:\n",
    "        metalista.append(constructor())\n",
    "        repite=input('¿Hay otra categoría más para cargar?: ')\n",
    "        if repite in ['si','SI']:\n",
    "            continue\n",
    "        else:\n",
    "            break\n",
    "    from tabulate import tabulate\n",
    "    return print(f'\\n\\n{tabulate(metalista, headers=[\"Categoría\", \"Cantidad\", \"Peso\", \"Valuación\"])}\\n\\nLos precios considerados son de la {fecha}')\n",
    "programa()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
