# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJ8FP6XYGnR27_NISJWv62HIpdJSvkDx
"""

import pandas as pd
import numpy as np
df=pd.read_html('https://www.monasterio-tattersall.com/precios-hacienda') #leo la tabla de la página
df[0] 
hacienda = df[0] #asigno una variable a la tabla
categoria = hacienda.Categoría #creo las series
promedio = hacienda.Promedio
tabla = pd.DataFrame({'categoria':categoria,'promedio':promedio}) #creo un dataframe con categoria y promedio
ternero=tabla[0:4] 
novillito=tabla[4:7]
ternera=tabla[7:11]
vaquillona=tabla[11:14]
vaca=tabla[19:20]
fecha=(tabla[24:25].values)[0][0]

#hacer una función que pida tipo, cantidad y peso y que devuelva cuando con los input y valuacion
tipo=input('ingrese tipo de hacienda: ')
if tipo == 'ternera':
  print(ternera)
elif tipo== 'ternero':
  print(ternero)
elif tipo== 'novillito':
  print(novillito)
elif tipo== 'vaquillona':
  print(vaquillona)
elif tipo== 'vaca':
  print(vaca)
else:
  print('No es una categoría válida')
print(f'Los precios considerados son de la {fecha}')

